import type { Metadata } from "next";
import { Geist, Geist_Mono, Prompt } from "next/font/google";
import "./globals.css";

const prompt = Prompt({
  variable: "--font-prompt-sans",
  subsets: ["latin"],
  weight: "100"
});



export const metadata: Metadata = {
  title: "Kasidate Portflolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${prompt.variable} ${prompt.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
